name: CI

on:
  push:
    branches: [ "branch_docker_olivier" ]
  pull_request:
    branches: [ "branch_docker_olivier" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ”„ Checkout code
      uses: actions/checkout@v4

    - name: ğŸ“¦ Install backend dependencies
      run: cd backend && npm install

    - name: ğŸ” Lint backend
      run: cd backend && npx eslint .

    - name: ğŸ“¦ Install frontend dependencies
      run: cd frontend && npm install

    - name: ğŸ” Lint frontend
      run: cd frontend && npx eslint .
